apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: cronj1
spec:
  schedule: "* * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: c1
            image: centos:6
            command: ['/bin/bash','-c','sleep 5']
          restartPolicy: Never
